version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 8080:8080
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 42
      POSTGRES_DB: nest
    networks:
      - innuendo
networks:
  innuendo: